name = "movies-backend"
compatibility_date = "2024-08-10"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "movies-db"
database_id = "427297ca-2bbb-408b-8866-e0b4ac7ff5ff"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"